### ISSUE TITLE
Convert Meetup recordings to blog posts

### ISSUE THREAD

**Issue by aakankshaduggal** [operate-first/operate-first-data-science-community#50]
Convert all the meetup recordings to blog posts. Explore resources, like https://www.rev.ai/

Acceptance Criteria - 
 Blog posts

**Comment by aakankshaduggal** [comment]
1. Video to text using youtube auto-generated transcript 
* [Document](https://docs.google.com/document/d/1xqFarSYKSjvBphkx-Esz5xiDyKl4TlVYb-Jo3GBnLyU/edit?usp=sharing)
* Faster and auto-generated

2. Video to text using rev.ai -
* [Document](https://docs.google.com/document/d/1GDSPX4i0lRtVZAKm63BRLN1HHa_crhqAzU6OHV2wn48/edit?usp=sharing)
* More accurate transcription
* Slower as compared to youtube transcripts
* Have to upload the video file to get the transcript.

**Comment by aakankshaduggal** [comment]
@MichaelClifford @oindrillac @chauhankaranraj @Shreyanand @hemajv @suppathak @erikerlandson 
In my opinion, we should go for the rev.ai tool to convert the meetups to blog. Please let me know what you all feel so we can start with pushing the content. Either way, we could use tools like Grammarly to resolve any grammatical issues if there are any.

**Comment by chauhankaranraj** [comment]
> @MichaelClifford @oindrillac @chauhankaranraj @Shreyanand @hemajv @suppathak @erikerlandson In my opinion, we should go for the rev.ai tool to convert the meetups to blog. Please let me know what you all feel so we can start with pushing the content. Either way, we could use tools like Grammarly to resolve any grammatical issues if there are any.

Both options seem quite similar to me in terms of accuracy on this particular video. However, I like that rev.ai is able to identify and track unique speakers (Speaker 0, 1, 2, etc), which could be useful for NLP applications in the future. So I'd vote rev.ai as well :)

**Comment by aakankshaduggal** [comment]
@hemajv @suppathak Thank you for adding yourselves to the issue. I was able to convert all these meetups to blog posts. What you all could help is with editing and proofreading these blogs before they make it to the website. I will share these blog posts on drive with you and we can split these amongst us :smile: 
Here's the [link](https://drive.google.com/file/d/1UH3KaiNQfIQAyOMQANkq33g7JO6_pEHA/view?usp=sharing) to all the converted blog posts.

**Comment by suppathak** [comment]
> Here's the [link](https://drive.google.com/file/d/1UH3KaiNQfIQAyOMQANkq33g7JO6_pEHA/view?usp=sharing) to all the converted blog posts.

@aakankshaduggal , The link takes me to only one .md file, and not all converted blog posts. Am I missing anything here?

**Comment by aakankshaduggal** [comment]
@suppathak - Sorry, my bad. I have updated the comment, please let me know if this works for you.
