### ISSUE TITLE
Promote the meetup

### ISSUE THREAD

**Issue by aakankshaduggal** [operate-first/operate-first-data-science-community#52]
- [ ] Send out regular updates on email, chat and slack
- [ ] Promote through twitter
- [ ] Create a new LinkedIn account for Operate First
- [ ] Host meetup on public platforms like meetup

**Comment by oindrillac** [comment]
Creating a meetup on meetup.com needs us to sign up for a plan.

<img width="684" alt="Screen Shot 2022-03-11 at 3 16 05 PM" src="https://user-images.githubusercontent.com/32435206/157954184-92d0d217-dbe7-44fa-b97a-8ab1bae491af.png">

Its free for 6 months and might become a paid plan after. Do we want to give it a try for 6 mos? 
Fyi: It needs a payment method on file to proceed. What are the thoughts on this?

**Comment by oindrillac** [comment]
Once this (https://github.com/aicoe-aiops/operate-first-data-science-community/issues/67) is ready, we can think about cross-promoting the blogs on multiple channels, internal red hat channels like next.red hat, rh research and external channels as well.
