### ISSUE TITLE
Video walkthrough explaining obfuscation techniques

### ISSUE THREAD

**Issue by suppathak** [operate-first/operate-first-data-science-community#55]
**Acceptance Criteria**

- [x] Create a video walk-through explaining different obfuscation techniques .

**Comment by suppathak** [comment]
Adding my meet-up video, where I have described the Obfuscation technique:

https://www.youtube.com/watch?v=aj-THe9fFIQ&t=596s

**Comment by suppathak** [comment]
@aakankshaduggal , I have added my meet-up presentation here, where I presented about Obfuscation techniques that was described in the notebook.

**Comment by aakankshaduggal** [comment]
Awesome, thank you @suppathak.
Closing this issue :rocket:
